<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<ul>
    <#list user as item>
        <li>${ item }</li>
    </#list>
</ul>

<form action="/discography" method="post">
    <div>
        <label for="bandname">Bandname</label>
        <input type="text" name="firstname" id="bandname">
    </div>
    <div>
        <label for="album">Album</label>
        <input type="text" name="album" id="album">
    </div>
    <button type="submit">Ajouter</button>
</form>

</body>
</html>